name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -tt -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "\
          cd ~/data && \
          sudo rm -rf nextjs-landing-page && \
          git clone --branch main --depth 1 git@github.com:reflense/nextjs-landing-page.git && \
          cd nextjs-landing-page && \
          git pull origin main && \
          docker compose down && \
          docker compose up -d --build 2>&1 1>/dev/null && \
          exit
        "